/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/common/Alert.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    CreateStudentModal: typeof import('./src/components/students/CreateStudentModal.vue')['default']
    DeleteStudentModal: typeof import('./src/components/students/DeleteStudentModal.vue')['default']
    Dialog: typeof import('./src/components/common/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/common/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/common/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/common/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/common/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/common/dialog/DialogHeader.vue')['default']
    DialogTitle: typeof import('./src/components/common/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/common/dialog/DialogTrigger.vue')['default']
    DropdownMenu: typeof import('./src/components/common/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuContent: typeof import('./src/components/common/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuItem: typeof import('./src/components/common/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./src/components/common/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuSeparator: typeof import('./src/components/common/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuTrigger: typeof import('./src/components/common/dropdown-menu/DropdownMenuTrigger.vue')['default']
    EditStudentModal: typeof import('./src/components/students/EditStudentModal.vue')['default']
    MobileSidebar: typeof import('./src/components/mobileSidebar/MobileSidebar.vue')['default']
    NavBar: typeof import('./src/components/navbar/NavBar.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/common/select/Select.vue')['default']
    SelectContent: typeof import('./src/components/common/select/SelectContent.vue')['default']
    SelectItem: typeof import('./src/components/common/select/SelectItem.vue')['default']
    SelectTrigger: typeof import('./src/components/common/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./src/components/common/select/SelectValue.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/Sidebar.vue')['default']
    SidebarCollapseButton: typeof import('./src/components/sidebar/SidebarCollapseButton.vue')['default']
    SidebarContent: typeof import('./src/components/sidebar/SidebarContent.vue')['default']
    SidebarHeader: typeof import('./src/components/sidebar/SidebarHeader.vue')['default']
    SidebarItem: typeof import('./src/components/sidebar/SidebarItem.vue')['default']
    Skeleton: typeof import('./src/components/common/skeleton/Skeleton.vue')['default']
    StudentsTable: typeof import('./src/components/students/StudentsTable.vue')['default']
    Table: typeof import('./src/components/common/table/Table.vue')['default']
    TableBody: typeof import('./src/components/common/table/TableBody.vue')['default']
    TableCaption: typeof import('./src/components/common/table/TableCaption.vue')['default']
    TableCell: typeof import('./src/components/common/table/TableCell.vue')['default']
    TableFooter: typeof import('./src/components/common/table/TableFooter.vue')['default']
    TableHead: typeof import('./src/components/common/table/TableHead.vue')['default']
    TableHeader: typeof import('./src/components/common/table/TableHeader.vue')['default']
    TableRow: typeof import('./src/components/common/table/TableRow.vue')['default']
  }
}
