<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Academic Transcript</title>
    <style>
        /* Estilos simples para PDF */
        body { font-family: Helvetica, Arial, sans-serif; font-size: 14px; }
        .header { text-align: center; margin-bottom: 25px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .student-info { margin-bottom: 20px; width: 100%; }
        .student-info td { padding: 4px; }
        table.grades { width: 100%; border-collapse: collapse; margin-top: 15px; }
        table.grades th, table.grades td { border: 1px solid #333; padding: 8px; text-align: left; }
        table.grades th { background-color: #f4f4f4; }
        .footer { margin-top: 50px; font-size: 12px; text-align: center; color: #777; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Academic Transcript</h2>
        <p>Official Grade Report</p>
    </div>

    <table class="student-info">
        <tr>
            <td><strong>Student:</strong> {{ $student->name }} {{ $student->lastname }}</td>
            <td><strong>Student ID:</strong> {{ $student->carnet }}</td>
        </tr>
        <tr>
            <td><strong>Program:</strong> {{ $student->career }}</td>
            <td><strong>Date:</strong> {{ date('Y-m-d') }}</td>
        </tr>
    </table>

    <table class="grades">
        <thead>
            <tr>
                <th>Semester</th>
                <th>Code</th>
                <th>Subject</th>
                <th>UV</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody>
            @foreach($registers as $register)
            <tr>
                <td>{{ $register->semester->year }} - Term {{ $register->semester->semester_number }}</td>
                <td>{{ $register->subject->code }}</td>
                <td>{{ $register->subject->name }}</td>
                <td>{{ $register->subject->uv }}</td>
                <td>{{ $register->grade }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Academic System API.</p>
    </div>
</body>
</html>
